ai.x.grok:
  app_name: "Grok Ai"
  description: 
    - "æ­£åœ¨å’ŒAiå¯¹çº¿"
    - "Aiå®åœ¨å¤ªå¥½ç”¨äº†ï¼Œä½ çŸ¥é“å—ï¼Ÿ"

android:
  app_name: "ç³»ç»Ÿæ¡Œé¢"
  description: "æ­£åœ¨æŒ‚æœºã€‚ã€‚ã€‚"

com.android.launcher:
  app_name: "ç³»ç»Ÿæ¡Œé¢"
  description: "å¯èƒ½å·²ç»ç¡è§‰å•° (_ã€€_)ã€‚ã‚œzï½šï¼º"
  is_disable: true

bin.mt.plus:
  app_name: "MTèµ„æºç®¡ç†å™¨"
  description: "å³ä½¿æ˜¯ç”¨æ‰‹æœºä¹Ÿè¦å†™å¥½ä»£ç "

tv.danmaku.bili:
  app_name: "å“”å“©å“”å“©"
  description: "è¦ä¹ˆåœ¨ä¸Šè¯¾ï¼Œè¦ä¹ˆåœ¨å•æ‰€åˆ·Bç«™ ï¼ï¸¿ï¼œ"

com.alibaba.android.rimet:
  app_name: "é’‰é’‰"
  description: 
    - "æ­£åœ¨å®Œæˆé’‰é’‰ä»»åŠ¡"
    - "åŠªåŠ›å·¥ä½œï¼Œè®¤çœŸé’‰é’‰ï¼( â€¢_â€¢)>âŒâ– -â–  (âŒâ– _â– )"
    - copy_by: "com.tencent.mobileqq"

mark.via:
  app_name: "Viaæµè§ˆå™¨"
  description: "è¿™æ˜¯æ‰‹æœºä¸Šæœ€å¥½çš„æµè§ˆå™¨äº†"

org.mozilla.firefox:
  app_name: "Firefoxæµè§ˆå™¨"
  description: "äº’è”ç½‘ä»è¿™é‡Œå¼€å§‹"

com.tencent.mobileqq:
  app_name: "QQ"
  description: 
    - "æ­£åœ¨åƒğŸ’© æ­£åœ¨æ¬ğŸ’©"
    - "å¿™ç€å’Œæœ‹å‹èŠå¤©å‘¢ï¼( â€¢_â€¢)>âŒâ– -â–  (âŒâ– _â– )"
    - "æ­£åœ¨æ€è€ƒå¦‚ä½•å›å¤ğŸ¤”"
    - "æ­£åœ¨å¤„ç†å¤§é‡æ¶ˆæ¯ğŸ“¨"
    - "è¯´ä¸å®šæˆ‘åœ¨å·²è¯»ä¸å›å‘¢"

com.tencent.mm:
  app_name: "å¾®ä¿¡"
  description: 
    copy_by: "com.tencent.mobileqq"

com.suda.yzune.wakeupschedule:
  app_name: "è¯¾è¡¨"
  description: "ä»Šå¤©é€ƒå“ªèŠ‚è¯¾å‘¢ï¼Ÿï¼ˆï¿£â–½ï¿£ï¼‰"

com.taobao.takbao:
  app_name: "æ·˜å®"
  description: "å‰æ‰‹ä¸­ã€‚ã€‚ã€‚(ï¿£ï¸¶ï¿£)"

com.github.android:
  app_name: "GitHubå®¢æˆ·ç«¯"
  description: "ä»€ä¹ˆæ—¶å€™æ‰èƒ½æˆä¸ºå¼€æºdalaoå•Šï¼Ÿ( è¶…æƒ³(à¸‡ â€¢_â€¢)à¸‡"

com.youdao.translator:
  app_name: "æœ‰é“ç¿»è¯‘å®˜"
  description: "æ­£åœ¨ç¿»è¯‘ã€‚ã€‚ã€‚"

com.oplus.securitypermission:
  app_name: "ç³»ç»Ÿå®‰å…¨ä¸­å¿ƒ"
  description: "ä¿æŠ¤æ‰‹æœºå®‰å…¨ï¼Œé˜²æ­¢ç—…æ¯’å…¥ä¾µ"

com.tencent.pokemonunite.cn:
  app_name: "å®å¯æ¢¦å¤§é›†ç»“"
  description: "é›†ç»“å§ï¼è®­ç»ƒå®¶ï¼Ù©(ËƒÌ¶ÍˆÌ€à¯°Ë‚Ì¶ÍˆÌ)Ùˆ"

org.telegram.messenger:
  app_name: "TG"
  description: "æ­£åœ¨éšè—èº«ä»½ã€‚ã€‚ã€‚"

com.openai.chatgpt:
  app_name: "ChatGPT"
  description: 
    - copy_by: "ai.x.grok"

com.ss.android.ugc.aweme:
  app_name: "æŠ–éŸ³"
  description: "è®°å½•ç¾å¥½ç”Ÿæ´» (â€¢Ì€á´—â€¢Ì)Ùˆ Ì‘Ì‘"

unknown:
  app_name: "æœªçŸ¥åº”ç”¨"
  description: "æ­£åœ¨ä½¿ç”¨æœªçŸ¥åº”ç”¨"

goland:
  app_name: "Golangå¼€å‘å·¥å…·"
  description: 
    - "æ­£åœ¨è§£é”å‰é¢çš„åŒºåŸŸÏ†(ã‚œâ–½ã‚œ*)â™ª"
    - copy_by: "Code.exe"

goland64.exe:
  app_name: "Golangå¼€å‘å·¥å…·"
  description:
    copy_by: "goland"

DingTalk.exe:
  app_name: "é’‰é’‰"
  description: "æ­£åœ¨å®Œæˆé’‰é’‰ä»»åŠ¡"

Code.exe:
  app_name: "Visual Studio Code"
  description: 
    - "æ­£åœ¨ç¼–å†™ä¸–ç•Œ Let't build from here ğŸŒ"
    - "å¾®è½¯å¤§æˆ˜ä»£ç ï¼ Microsoft VS Code ğŸ’»"
    - 
      <-: "ä»Šæ™šå’Œä»£ç å†³ä¸€æ­»æˆ˜ï¼"
      6:00-12:00: "ç¾å¥½çš„ä¸€å¤©ä»codingå¼€å§‹ï¼"
      12:00-21:00: "äº«å—ç¼–ç¨‹çš„ä¹è¶£å§ï¼"
      ->: "æ­£åœ¨ä¿®å¤ä¸€ä¸ªbugï¼Œå“"
      1: ""

firefox.exe:
  app_name: "Firefoxæµè§ˆå™¨"
  description: 
    - "æ¢ç´¢äº’è”ç½‘çš„æ— é™å¯èƒ½"
    - "äº’è”ç½‘ç²¾ç¥çš„èµ·æº"
    - "æ­£åœ¨è®¿é—®ç¥ç§˜ç½‘é¡µ"
    - "æ­£åœ¨æµè§ˆä¸–é—´ä¸€åˆ‡ç¾å¥½äº‹ç‰©"
    - "æ— è§†é£é™©ï¼Œç»§ç»­è®¿é—®"

QQMusic.exe:
  app_name: "QQéŸ³ä¹"
  description: 
    - "æ­£åœ¨è†å¬ç¾å¦™çš„éŸ³ä¹"
    - "éŸ³ä¹è®©ç”Ÿæ´»æ›´ç¾å¥½ ğŸµ"
    - "ğŸµ~ğŸ¶~~~"

Weixin.exe:
  app_name: "å¾®ä¿¡"
  description: 
    - "ä¼¼ä¹åœ¨èŠæ­£ç»äº‹å„¿"
    - copy_by: "com.tencent.mobileqq"

QQ.exe:
  app_name: "QQ"
  description: 
    copy_by: "com.tencent.mobileqq"

notepad++.exe:
  app_name: "Notepad++"
  description: "è®°å½•æˆ‘çš„ä¸´æ—¶è‰ç¨¿"

python.exe:
  app_name: "Pythonè§£é‡Šå™¨"
  description: "äººç”Ÿè‹¦çŸ­ï¼Œæˆ‘ç”¨Python"

explorer.exe:
  app_name: "æ–‡ä»¶èµ„æºç®¡ç†å™¨"
  description: "æ­£åœ¨æ•´ç†æ–‡ä»¶å¤¹"
  is_disable: true

cmd.exe:
  app_name: "å‘½ä»¤æç¤ºç¬¦"
  description: "æ­£åœ¨æ‰§è¡Œå‘½ä»¤"

powershell.exe:
  app_name: "PowerShell"
  description: "æ­£åœ¨æ‰§è¡Œè„šæœ¬ä»»åŠ¡"

EXCEL.EXE:
  app_name: "Microsoft Excel"
  description: "æ­£åœ¨å¤„ç†æ•°æ®è¡¨æ ¼"

navigator.exe:
  app_name: "æ•°æ®åº“æµè§ˆå™¨"
  description: "TMDï¼Œæ•°æ®åº“åˆå´©äº†ï¼ ï¼ˆï¸¶^ï¸¶ï¼‰"

navicat.exe:
  app_name: "æ•°æ®åº“æµè§ˆå™¨"
  description: "TMDï¼Œæ•°æ®åº“åˆå´©äº†ï¼ ï¼ˆï¸¶^ï¸¶ï¼‰"

obsidian.exe:
  app_name: "Obsidianç¬”è®°"
  description: "æ­£åœ¨æ•´ç†æˆ‘çš„çŸ¥è¯†åº“"

steam.exe:
  app_name: "Steamæ¸¸æˆå¹³å°"
  description: "æ¥å’Œ oneekac ä¸€èµ·ç©å§ï¼"

Taskmgr.exe:
  app_name: "ä»»åŠ¡ç®¡ç†å™¨"
  description: "å¯æ¶ï¼Œåˆæ˜¯å“ªä¸ªè¿›ç¨‹å ç”¨äº†è¿™ä¹ˆå¤šèµ„æºï¼"

v2rayN.exe:
  app_name: "v2rayN"
  description: 
    - "æœºé•¿èµ·é£ï¼ŒğŸ›«..."
    - "èµ·é£å•°ğŸ›«"

FocusWindowMonitor.exe:
  app_name: "FocusWindowç›‘æ§"
  description: 
    - "è§†å¥¸æˆ‘çš„æ¯ä¸€åˆ»"
    - "ä½¿ç”¨pythonè·å–å½“å‰æ•°æ®ï¼Œä»“åº“ï¼šgithub.com/Bluore/CheckMe-Client-Python"

XTerminal.exe:
  app_name: "XTerminalç»ˆç«¯"
  description: "æ­£åœ¨å’ŒæœåŠ¡å™¨æ–—æ™ºæ–—å‹‡ãƒ½ï¼ˆâ‰§â–¡â‰¦ï¼‰ãƒ"

WindowsTerminal.exe:
  app_name: "Windowsç»ˆç«¯"
  description: "å°å°ç»ˆç«¯ï¼Œå¤§å¤§ä¸–ç•Œ"

Apifox.exe:
  app_name: "ApiFoxæ¥å£è°ƒè¯•"
  description: "æ­£åœ¨è°ƒè¯•æ¥å£ï¼Œåˆ«æ‰“æ‰°æˆ‘ï¼(* ï¿£ï¸¿ï¿£)"

Postman.exe:
  app_name: "Postmanæ¥å£è°ƒè¯•"
  description: "æ­£åœ¨è°ƒè¯•æ¥å£ï¼Œåˆ«æ‰“æ‰°æˆ‘ï¼(* ï¿£ï¸¿ï¿£)"

Typora.exe:
  app_name: "Typoraå†™ä½œå·¥å…·"
  description: "è®°ç¬”è®° è®°ç¬”è®° U_U"

coodesker-x64.exe:
  app_name: "Coodeskeræ¡Œé¢ç®¡ç†"
  description: "å“ˆå“ˆ æˆ‘çš„æ¡Œé¢å¤ªå¥½çœ‹äº†ï¼æˆ‘è¦çœ‹ä¸€è¾ˆå­æˆ‘çš„æ¡Œé¢ <(ï¿£ï¸¶ï¿£)â†—[LOOK!]>"

å“”å“©å“”å“©.exe:
  app_name: "å“”å“©å“”å“©"
  description: "å“”å“©å“”å“© (ã‚œ-ã‚œ)ã¤ãƒ­ å¹²æ¯~-bilibili"
  is_hide_music: true

chrome.exe:
  app_name: "è°·æ­Œæµè§ˆå™¨"
  description: 
    - "æ­£åœ¨åšWebå¼€å‘ å“ï¼ŒçœŸè„±å‘"
    - copy_by: "firefox.exe"

PotPlayerMini64.exe:
  app_name: "PotPlayeræ’­æ”¾å™¨"
  description: "æ­£åœ¨çœ‹ä»€ä¹ˆç”µå½±å‘¢ï¼Ÿ"

wegame.exe:
  app_name: "WeGameæ¸¸æˆå¹³å°"
  description: "èœé€¼ï¼Œæ±‚å¸¦é£ï¼"

LeagueClientUx.exe:
  app_name: "è‹±é›„è”ç›Ÿå®¢æˆ·ç«¯"
  description: 
    - "å†²å‘€ï¼æ–¯è«å¾·ï¼ï¼ï¼ <(ï¿£ï¸¶ï¿£)â†—[GO!]"
    - copy_by: "wegame.exe"

vmware.exe:
  app_name: "VMWare"
  description: "æ­£åœ¨è¿è¡Œè™šæ‹Ÿæœº ( â€¢_â€¢)>âŒâ– -â–  (âŒâ– _â– )"

OneCommander.exe:
  app_name: "OneCommanderæ–‡ä»¶ç®¡ç†å™¨"
  description: "æ­£åœ¨æ•´ç†æ–‡ä»¶å¤¹"

java.exe:
  app_name: "Minecraft"
  description: "ä¸€èµ·æ¥ç©å•Šï¼(à¸‡ â€¢_â€¢)à¸‡ id:Bluore"

Plain Craft Launcher 2.exe:
  app_name: "Minecraftå¯åŠ¨å™¨"
  description: 
    - "Minecraft å¯åŠ¨! å‡†å¤‡è¿›å…¥æ–¹å—ä¸–ç•Œï¼"
    - copy_by: "java.exe"

lghub.exe:
  app_name: "Logitech G HUB"
  description: 
    - "æ­£åœ¨è°ƒæ•´é¼ æ ‡é”®ç›˜ç¯å…‰æ•ˆæœ"
    - "å¯æ¶çš„é©±åŠ¨ï¼Œåˆå‡ºé—®é¢˜äº†ï¼"

PixPin.exe:
  app_name: "PixPin"
  description: "å–„ç”¨æˆªå›¾è½¯ä»¶ ä¿æŠ¤çœ¼é•œ ğŸ‘€"

LockApp.exe:
  app_name: "é”å±ç•Œé¢"
  description: "æ­£åœ¨é”å±ã€‚ã€‚ã€‚"
  is_disable: true



test1:
  app_name: "disableæµ‹è¯•"
  description: "disableæµ‹è¯•"
  is_disable: true

test2:
  app_name: "åˆ—è¡¨éšæœºæµ‹è¯•"
  description:
    - "1"
    - "2"
    - "3"
    - "4"

test3:
  app_name: "æƒé‡éšæœºæµ‹è¯•"
  description:
    2: "2/3"
    1: "1/3"

test4:
  app_name: "æ—¥æœŸæµ‹è¯•"
  description:
    <-: "12:45ä¹‹å‰"
    12:45-13:50: "12:45-13:50ä¹‹é—´"
    ->: "13:50ä¹‹å"
    1: ""

test5:
  app_name: "æ–‡æœ¬å’Œé…ç½®æ‹·è´æµ‹è¯•"
  description:
    text: "æµ‹è¯•3: "
    copy_by: "test3"

test6:
  app_name: "å¥—å¨ƒæµ‹è¯•"
  description:
    text_1: "test: "
    text_2:
      <-:
        - "æ—©äº12:00çš„éšæœºæ•°1"
        - "æ—©äº12:00çš„éšæœºæ•°2"
      12:00-19:00:
        99: "å½“å‰æ—¶é—´åœ¨12:00-19:00ä¹‹é—´"
        1:
          <-:
            - "è¿æ°”å¤Ÿäº†ï¼Œæ—¶æœºæ²¡å¯¹"
            - "æ¥æ—©äº†"
          15:00-15:00: "ä½ æ˜¯å¹¸è¿ä¹‹æ˜Ÿ"
          ->:
            - "æ¥æ™šäº†"
            - copy_by: "test1"
          1: ""
      ->: "ä¸‹æ¬¡æ—©ç‚¹æ¥"
      1: ""


test:
  app_name: "ç»¼åˆæµ‹è¯•"
  description:
    text_1: "ç»¼åˆæµ‹è¯•"
    text_1_1: " test1:"
    text_1_2:
      copy_by: "test1"
    text_2_1: " test2:"
    text_2_2:
      copy_by: "test2"
    text_3_1: " test3:"
    text_3_2:
      copy_by: "test3"
    text_4_1: " test4:"
    text_4_2:
      copy_by: "test4"
    text_5_1: " test5:"
    text_5_2:
      copy_by: "test5"
