ai.x.grok:
  app_name: "Grok Ai"
  description: "æ­£åœ¨å’ŒGrok Aiå¯¹çº¿"

android:
  app_name: "ç³»ç»Ÿæ¡Œé¢"
  description: "æ­£åœ¨æŒ‚æœºã€‚ã€‚ã€‚"

com.android.launcher:
  app_name: "ç³»ç»Ÿæ¡Œé¢"
  description: "å¯èƒ½å·²ç»ç¡è§‰å•° (_ã€€_)ã€‚ã‚œzï½šï¼º"

bin.mt.plus:
  app_name: "MTèµ„æºç®¡ç†å™¨"
  description: "å³ä½¿æ˜¯ç”¨æ‰‹æœºä¹Ÿè¦å†™å¥½ä»£ç "

tv.danmaku.bili:
  app_name: "å“”å“©å“”å“©"
  description: "è¦ä¹ˆåœ¨ä¸Šè¯¾ï¼Œè¦ä¹ˆåœ¨å•æ‰€åˆ·Bç«™ ï¼ï¸¿ï¼œ"

com.alibaba.android.rimet:
  app_name: "é’‰é’‰"
  description: "æ­£åœ¨å®Œæˆé’‰é’‰ä»»åŠ¡"

mark.via:
  app_name: "Viaæµè§ˆå™¨"
  description: "è¿™æ˜¯æ‰‹æœºä¸Šæœ€å¥½çš„æµè§ˆå™¨äº†"

com.tencent.mobileqq:
  app_name: "QQ"
  description: "æ­£åœ¨åƒğŸ’© æ­£åœ¨æ¬ğŸ’©"

com.suda.yzune.wakeupschedule:
  app_name: "è¯¾è¡¨"
  description: "ä»Šå¤©é€ƒå“ªèŠ‚è¯¾å‘¢ï¼Ÿï¼ˆï¿£â–½ï¿£ï¼‰"

com.taobao.takbao:
  app_name: "æ·˜å®"
  description: "å‰æ‰‹ä¸­ã€‚ã€‚ã€‚(ï¿£ï¸¶ï¿£)"

com.github.android:
  app_name: "GitHubå®¢æˆ·ç«¯"
  description: "ä»€ä¹ˆæ—¶å€™æ‰èƒ½æˆä¸ºå¼€æºdalaoå•Šï¼Ÿ( è¶…æƒ³(à¸‡ â€¢_â€¢)à¸‡"

goland:
  app_name: "Golangå¼€å‘å·¥å…·"
  description: "æ­£åœ¨è§£é”å‰é¢çš„åŒºåŸŸÏ†(ã‚œâ–½ã‚œ*)â™ª"

goland64.exe:
  app_name: "Golangå¼€å‘å·¥å…·"
  description: "æ­£åœ¨è§£é”å‰é¢çš„åŒºåŸŸÏ†(ã‚œâ–½ã‚œ*)â™ª"

DingTalk.exe:
  app_name: "é’‰é’‰"
  description: "æ­£åœ¨å®Œæˆé’‰é’‰ä»»åŠ¡"

Code.exe:
  app_name: "Visual Studio Code"
  description: "æ­£åœ¨ç¼–å†™ä¸–ç•Œ Let't build from here ğŸŒ"

firefox.exe:
  app_name: "Firefoxæµè§ˆå™¨"
  description: "æ­£åœ¨æµè§ˆä¸–é—´ä¸€åˆ‡ç¾å¥½äº‹ç‰©"

QQMusic.exe:
  app_name: "QQéŸ³ä¹"
  description: "æ­£åœ¨è†å¬ç¾å¦™çš„éŸ³ä¹"

Weixin.exe:
  app_name: "å¾®ä¿¡"
  description: "ä¼¼ä¹åœ¨èŠæ­£ç»äº‹å„¿"

QQ.exe:
  app_name: "QQ"
  description: "æ­£åœ¨æ€è€ƒå¦‚ä½•å›å¤ğŸ¤”"

notepad++.exe:
  app_name: "Notepad++"
  description: "è®°å½•æˆ‘çš„ä¸´æ—¶è‰ç¨¿"

python.exe:
  app_name: "Pythonè§£é‡Šå™¨"
  description: "äººç”Ÿè‹¦çŸ­ï¼Œæˆ‘ç”¨Python"

explorer.exe:
  app_name: "æ–‡ä»¶èµ„æºç®¡ç†å™¨"
  description: "æ­£åœ¨æ•´ç†æ–‡ä»¶å¤¹"

cmd.exe:
  app_name: "å‘½ä»¤æç¤ºç¬¦"
  description: "æ­£åœ¨æ‰§è¡Œå‘½ä»¤"

powershell.exe:
  app_name: "PowerShell"
  description: "æ­£åœ¨æ‰§è¡Œè„šæœ¬ä»»åŠ¡"

EXCEL.EXE:
  app_name: "Microsoft Excel"
  description: "æ­£åœ¨å¤„ç†æ•°æ®è¡¨æ ¼"

navigator.exe:
  app_name: "æ•°æ®åº“æµè§ˆå™¨"
  description: "TMDï¼Œæ•°æ®åº“åˆå´©äº†ï¼ ï¼ˆï¸¶^ï¸¶ï¼‰"

obsidian.exe:
  app_name: "Obsidianç¬”è®°"
  description: "æ­£åœ¨æ•´ç†æˆ‘çš„çŸ¥è¯†åº“"

steam.exe:
  app_name: "Steamæ¸¸æˆå¹³å°"
  description: "æ¥å’Œ oneekac ä¸€èµ·ç©å§ï¼"

Taskmgr.exe:
  app_name: "ä»»åŠ¡ç®¡ç†å™¨"
  description: "å¯æ¶ï¼Œåˆæ˜¯å“ªä¸ªè¿›ç¨‹å ç”¨äº†è¿™ä¹ˆå¤šèµ„æºï¼"

v2rayN.exe:
  app_name: "v2rayN"
  description: "æœºé•¿èµ·é£ï¼ŒğŸ›«..."

FocusWindowMonitor.exe:
  app_name: "FocusWindowç›‘æ§"
  description: "è§†å¥¸æˆ‘çš„æ¯ä¸€åˆ»"

XTerminal.exe:
  app_name: "XTerminalç»ˆç«¯"
  description: "æ­£åœ¨å’ŒæœåŠ¡å™¨æ–—æ™ºæ–—å‹‡ãƒ½ï¼ˆâ‰§â–¡â‰¦ï¼‰ãƒ"

WindowsTerminal.exe:
  app_name: "Windowsç»ˆç«¯"
  description: "å°å°ç»ˆç«¯ï¼Œå¤§å¤§ä¸–ç•Œ"

Apifox.exe:
  app_name: "ApiFoxæ¥å£è°ƒè¯•"
  description: "æ­£åœ¨è°ƒè¯•æ¥å£ï¼Œåˆ«æ‰“æ‰°æˆ‘ï¼(* ï¿£ï¸¿ï¿£)"

Postman.exe:
  app_name: "Postmanæ¥å£è°ƒè¯•"
  description: "æ­£åœ¨è°ƒè¯•æ¥å£ï¼Œåˆ«æ‰“æ‰°æˆ‘ï¼(* ï¿£ï¸¿ï¿£)"

Typora.exe:
  app_name: "Typoraå†™ä½œå·¥å…·"
  description: "è®°ç¬”è®° è®°ç¬”è®° U_U"

coodesker-x64.exe:
  app_name: "Coodeskeræ¡Œé¢ç®¡ç†"
  description: "å“ˆå“ˆ æˆ‘çš„æ¡Œé¢å¤ªå¥½çœ‹äº†ï¼æˆ‘è¦çœ‹ä¸€è¾ˆå­æˆ‘çš„æ¡Œé¢ <(ï¿£ï¸¶ï¿£)â†—[LOOK!]>"

å“”å“©å“”å“©.exe:
  app_name: "å“”å“©å“”å“©"
  description: "å“”å“©å“”å“© (ã‚œ-ã‚œ)ã¤ãƒ­ å¹²æ¯~-bilibili"
  is_hide_music: true

chrome.exe:
  app_name: "è°·æ­Œæµè§ˆå™¨"
  description: "æ­£åœ¨åšWebå¼€å‘ å“ï¼ŒçœŸè„±å‘"

PotPlayerMini64.exe:
  app_name: "PotPlayeræ’­æ”¾å™¨"
  description: "æ­£åœ¨çœ‹ä»€ä¹ˆç”µå½±å‘¢ï¼Ÿ"

wegame.exe:
  app_name: "WeGameæ¸¸æˆå¹³å°"
  description: "èœé€¼ï¼Œæ±‚å¸¦é£ï¼"

LeagueClientUx.exe:
  app_name: "è‹±é›„è”ç›Ÿå®¢æˆ·ç«¯"
  description: "å†²å‘€ï¼æ–¯è«å¾·ï¼ï¼ï¼ <(ï¿£ï¸¶ï¿£)â†—[GO!]"